# Generated by Django 2.2.5 on 2020-09-27 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200920_0035'),
        ('conversations', '0002_conversation_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='reservation',
        ),
        migrations.AddField(
            model_name='conversation',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='rooms.Room'),
        ),
    ]
