# Generated by Django 2.2.5 on 2020-09-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_auto_20200927_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='room',
        ),
    ]
