# Generated by Django 2.2.5 on 2020-09-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_bookedday'),
        ('conversations', '0006_remove_conversation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='reservation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='reservations.Reservation'),
        ),
    ]
