# Generated by Django 2.2.5 on 2020-09-27 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_remove_conversation_reservation'),
        ('reservations', '0002_bookedday'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='conversation',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='conversations.Conversation'),
        ),
    ]
