# Generated by Django 2.2.5 on 2020-09-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='conversation',
        ),
    ]
